### ISSUE TITLE
perl script points to wrong folder

### ISSUE THREAD

**Issue by krisavi** [elasticfence/docker-kibi#1]
In entrypoint.sh, the perl replacement points to wrong location:
```
perl -p -i -e "s/9220/9200/" /opt/kibi/kibi/config/kibi.yml
perl -p -i -e "s/localhost/0.0.0.0/" /opt/kibi/kibi/config/kibi.yml
```

correct folder is /opt/kibi/config/kibi.yml

same seems to be the issue in Dockerfile
`ENV PATH /opt/kibi/kibi/bin:$PATH`

**Comment by lmangani** [comment]
Good Catch! I mostly only use the elasticfence version with all plugins, so it was unnoticed :)
Thanks @krisavi
